using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace Salvavida.Generator
{
    public class BasicCodeGenerator : ICodeGenerator
    {
        internal readonly string[] AlternateNameTemplates = new[] { "Sv{0}", "{0}Ob" };
        protected CodeGenInfoStore? _infoStore;

        public virtual bool CanGenerate(CodeGenerationContext ctx) => true;

        public string Generate(CodeGenerationContext ctx)
        {
            _infoStore = new CodeGenInfoStore();
            var alreadySR = CodeGenHelper.GetIsAlreadySavableRoot(ctx.TypeSymbol);
            if (!alreadySR && CodeGenHelper.GetIsSavableRoot(ctx.TypeSymbol, true))
            {
                if (CodeGenHelper.GetHasBaseClasse(ctx.TypeSymbol))
                    _infoStore.generateSerializeRootMode++;
                _infoStore.generateSerializeRootMode++;
            }
            try
            {
                var sb = new ScriptBuilder();
                sb.WriteLine("// <auto-generated/>");
                sb.WriteLine("// This code is Generated by Salvavida Library.");
                sb.WriteLine("#nullable disable");
                sb.WriteLine("#pragma warning disable");
                sb.WriteLine("using Salvavida;");
                sb.WriteLine("using System.Collections.Generic;");
                WriteUsings(sb, ctx);
                sb.WriteLine();
                BeforeWriteNamespace(sb, ctx);
                WriteNamespace(sb, ctx, out var nsIndent);
                BeforeWriteClass(sb, ctx);
                WriteClass(sb, ctx);
                WriteClassBody(sb, ctx);
                sb.EndCurlyBrackets();
                if (nsIndent) sb.EndCurlyBrackets();
                return sb.ToString();
            }
            finally
            {
                _infoStore = null;
            }
        }

        private void WriteNamespace(ScriptBuilder sb, CodeGenerationContext ctx, out bool hasCurlyBrackets)
        {
            hasCurlyBrackets = false;
            var ns = ctx.TypeSymbol.ContainingNamespace;
            if (ns == null || ns.IsGlobalNamespace)
                return;

            if (ctx.LanguageVersion >= LanguageVersion.CSharp10)
            {
                sb.WriteLine($"namespace {ns.ToDisplayString()};");
                sb.WriteLine();
            }
            else
            {
                sb.WriteLine($"namespace {ns.ToDisplayString()}");
                sb.BeginCurlyBrackets(true);
                hasCurlyBrackets = true;
            }
        }

        private void WriteClass(ScriptBuilder sb, CodeGenerationContext ctx)
        {
            var className = ctx.TypeSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            _infoStore!.className = className;

            sb.Write($"sealed partial class {className} : ");
            if (_infoStore!.generateSerializeRootMode > 0)
            {
                if (_infoStore!.generateSerializeRootMode == 1)
                    sb.Write("Salvavida.DefaultImpl.SerializeRoot, ", true);
                else
                {
                    sb.Write(CodeGenHelper.INTERFACE_NAME_ISERIALIZEROOT, true);
                    sb.Write(", ", true);
                }
            }
            sb.Write($"ISavable<{className}>", true);
            sb.WriteLine();
            sb.BeginCurlyBrackets();
        }

        protected virtual void WriteUsings(ScriptBuilder sb, CodeGenerationContext ctx)
        {
        }

        protected virtual void BeforeWriteNamespace(ScriptBuilder sb, CodeGenerationContext ctx)
        {
        }

        protected virtual void BeforeWriteClass(ScriptBuilder sb, CodeGenerationContext ctx)
        {
        }

        protected virtual void WriteClassBody(ScriptBuilder sb, CodeGenerationContext ctx)
        {
            WriteImplementationsHead(sb, ctx);
            var typeSymbol = ctx.TypeSymbol;
            var membersList = new List<ISymbol>();
            ITypeSymbol? parentType = typeSymbol;
            var i = 0;
            while (parentType != null)
            {
                IEnumerable<ISymbol> mems = parentType.GetMembers();
                if (i++ > 0)
                    mems = mems.Where(x => x.DeclaredAccessibility != Accessibility.Private);
                foreach (var mem in mems)
                {
                    membersList.Add(mem);
                    _infoStore!.existingPropertyNames.Add(mem.Name);
                }
                parentType = parentType.BaseType;
            }

            var allMembers = membersList.ToImmutableArray();

            foreach (var member in allMembers)
            {
                if (member is not IFieldSymbol fieldSymbol)
                    continue;
                HandleField(sb, fieldSymbol, ctx);
            }

            foreach (var member in allMembers)
            {
                if (member is not IPropertySymbol propSymbol)
                    continue;
                HandleProperty(sb, propSymbol, ctx);
            }

            foreach (var member in allMembers)
            {
                if (member is not IMethodSymbol methodSymbol)
                    continue;
                HandleMethod(sb, methodSymbol, ctx);
            }

            WriteImplementationsFoot(sb, ctx);
        }

        protected virtual void HandleField(ScriptBuilder sb, IFieldSymbol field, CodeGenerationContext ctx)
        {
            if (field.IsReadOnly || field.IsAbstract || field.IsConst || field.IsStatic)
                return;
            HandleFieldOrProp(sb, field, ctx);
        }

        protected virtual void HandleProperty(ScriptBuilder sb, IPropertySymbol prop, CodeGenerationContext ctx)
        {
            if (prop.IsReadOnly || prop.IsIndexer || prop.IsWriteOnly || prop.IsAbstract || prop.IsStatic)
                return;
            HandleFieldOrProp(sb, prop, ctx);
        }

        protected void HandleFieldOrProp(ScriptBuilder sb, ISymbol symbol, CodeGenerationContext ctx)
        {
            AttributeData? propNameAttr = null;
            AttributeData? ignoreAttr = null;
            AttributeData? saveSeparatelyAttr = null;
            AttributeData? lazyLoadAttr = null;

            var attrs = symbol.GetAttributes();

            foreach (var attrData in attrs)
            {
                var attrSymbol = attrData.AttributeClass!;
                var attrName = attrSymbol.ToDisplayString();
                if (attrName == CodeGenHelper.PROPERTY_NAME_ATTRIBUTE_NAME)
                    propNameAttr = attrData;
                else if (attrName == CodeGenHelper.IGNORE_ATTRIBUTE_NAME)
                    ignoreAttr = attrData;
                else if (attrName == CodeGenHelper.SAVE_SEPARATELY_ATTRIBUTE_NAME)
                    saveSeparatelyAttr = attrData;
                else if (attrName == "Salvavida.LazyLoadAttribute")
                    lazyLoadAttr = attrData;
            }

            if (ignoreAttr != null)
                return;

            string? attrPropName = null;
            if (propNameAttr != null)
            {
                var nameArg = propNameAttr.ConstructorArguments[0];
                attrPropName = nameArg.Value as string;
            }

            var fieldName = symbol.Name;
            if (string.IsNullOrEmpty(fieldName))
                return;
            string propertyName;
            if (string.IsNullOrEmpty(attrPropName))
            {
                var tempName = CodeGenHelper.GetPropertyName(fieldName.AsSpan());
                if (string.IsNullOrEmpty(tempName))
                {
                    ctx.SourceProductionContext.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.InvalidMemberName,
                        propNameAttr!.ApplicationSyntaxReference?.GetSyntax().GetLocation(), fieldName));
                    return;
                }
                else
                    propertyName = tempName!;
            }
            else
            {
                propertyName = attrPropName!;
            }

            var templateIndex = 0;
            while (_infoStore!.existingPropertyNames.Contains(propertyName))
            {
                if (templateIndex >= AlternateNameTemplates.Length)
                {
                    ctx.SourceProductionContext.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.AllCandidateNamesAreUnavailable,
                        symbol.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax().GetLocation(), fieldName));
                    return;
                }

                propertyName = string.Format(AlternateNameTemplates[templateIndex++], propertyName);
            }

            _infoStore!.existingPropertyNames.Add(propertyName);

            var typeSymbol = symbol switch
            {
                IFieldSymbol fs => fs.Type,
                IPropertySymbol ps => ps.Type,
                _ => throw new NotSupportedException(symbol.GetType().Name)
            };

            var collectionType = CodeGenHelper.GetCollectionType(ctx, typeSymbol, out var elemTypeSymbols);
            var saveSeparately = saveSeparatelyAttr != null;
            _infoStore!.nameMappings[fieldName] = propertyName;
            if (collectionType == CollectionType.None)
            {
                _infoStore.propTypeMappings[fieldName] = typeSymbol;
                if (saveSeparately)
                {
                    _infoStore!.separatedProperties.Add(propertyName);
                }
                var isSavable = IsTypeISavable(typeSymbol);
                if (isSavable)
                    _infoStore!.savableMembers.Add(propertyName);
                WriteProperty(sb, ctx, propertyName, fieldName, typeSymbol, isSavable, saveSeparately);
            }
            else
            {
                _infoStore!.collectionParameterMappings[fieldName] = (collectionType, elemTypeSymbols);
                if (saveSeparately)
                {
                    //var savableElement = CodeGenHelper.TryGetAttribute(ctx, , SalvavidaGenerator.SALVAVIDA_ATTRIBUTE)
                    // TODO: to check if elemTypeSymbols.Last() implemented ISavable or not
                    _infoStore!.separatedCollections.Add(propertyName);
                }
                else
                    _infoStore!.nonSeparatedCollections.Add(propertyName);

                _infoStore!.savableMembers.Add(propertyName);
                var collectionTypeString = GetCollectionTypeString(collectionType, elemTypeSymbols);
                var concreteTypeString = GetCollectionConcreteTypeString(collectionType, elemTypeSymbols);
                var elemTypeString = elemTypeSymbols.Last().ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var isSavable = IsTypeISavable(elemTypeSymbols.Last());
                WriteCollectionProperty(sb, ctx, propertyName, fieldName,
                    typeSymbol, collectionTypeString, concreteTypeString, elemTypeString, saveSeparately, isSavable, lazyLoadAttr);
            }
        }

        protected virtual void HandleMethod(ScriptBuilder sb, IMethodSymbol method, CodeGenerationContext ctx)
        {
        }

        protected bool IsTypeISavable(ITypeSymbol typeSymbol)
        {
            if (!_infoStore!.savableTypes.TryGetValue(typeSymbol, out var result))
            {
                result = CodeGenHelper.GetIsSavable(typeSymbol);
                _infoStore!.savableTypes[typeSymbol] = result;
            }

            return result;
        }

        protected virtual void WriteProperty(ScriptBuilder sb, CodeGenerationContext ctx, string propertyName, string fieldName, ITypeSymbol typeSymbol, bool isSavable, bool saveSeparately)
        {
            var typeFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            AddAttributePreventSerialize(sb, false);
            sb.WriteLine($"public {typeFullName} {propertyName}");
            var savabeType = IsTypeISavable(typeSymbol);
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine($"get => {fieldName};");

                sb.WriteLine("set");
                using (sb.CurlyBracketsScope())
                {
                    sb.WriteLine($"if (!EqualityComparer<{typeFullName}>.Default.Equals({fieldName}, value))");
                    using (sb.CurlyBracketsScope())
                    {
                        if (savabeType)
                            sb.WriteLine($"UnwatchChild({fieldName});");
                        sb.WriteLine($"{fieldName} = value;");
                        if (savabeType)
                            sb.WriteLine($"WatchChild(value, \"{propertyName}\");");
                        sb.WriteLine($"OnPropertyChanged(value, \"{propertyName}\");");
                    }
                }
            }

            sb.WriteLine();
        }

        protected virtual void WriteCollectionProperty(ScriptBuilder sb, CodeGenerationContext ctx, string propertyName, string fieldName,
            ITypeSymbol typeSymbol, string collectionTypeString, string concreteTypeString, string elemTypeString, bool saveSeparately, bool isSavable, AttributeData? lazyLoadAttr)
        {
            if (lazyLoadAttr != null && isSavable)
            {
                int threshold = 1000;
                int pageSize = 100;
                int maxCachedPages = 10;
                string cacheStrategy = "LRU";

                foreach (var namedArg in lazyLoadAttr.NamedArguments)
                {
                    switch (namedArg.Key)
                    {
                        case "Threshold": threshold = (int)namedArg.Value.Value!; break;
                        case "PageSize": pageSize = (int)namedArg.Value.Value!; break;
                        case "MaxCachedPages": maxCachedPages = (int)namedArg.Value.Value!; break;
                        case "CacheStrategy": cacheStrategy = namedArg.Value.Value!.ToString()!; break;
                    }
                }

                sb.WriteLine($"private static readonly LazyLoadConfig s_{fieldName}Config = new LazyLoadConfig");
                sb.WriteLine("{");
                sb.WriteLine($"    Threshold = {threshold},");
                sb.WriteLine($"    PageSize = {pageSize},");
                sb.WriteLine($"    MaxCachedPages = {maxCachedPages},");
                sb.WriteLine($"    CacheStrategy = CacheStrategy.{cacheStrategy}");
                sb.WriteLine("};");
                sb.WriteLine();
            }

            AddAttributePreventSerialize(sb, false);
            sb.WriteLine($"private {collectionTypeString} {fieldName}Ob;");
            AddAttributePreventSerialize(sb, false);
            sb.WriteLine($"public {collectionTypeString} {propertyName}");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine($"get");
                using (sb.CurlyBracketsScope())
                {
                    sb.WriteLine($"if ({fieldName} == null) return null;");
                    sb.WriteLine($"TryInit{propertyName}();");
                    sb.WriteLine($"return {fieldName}Ob;");
                }
            }

            sb.WriteLine();
            sb.WriteLine($"public void Set{propertyName}({typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} val)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine($"TryInit{propertyName}();");
                sb.WriteLine($"{fieldName}Ob.SwapSource(val);");
                sb.WriteLine($"{fieldName} = val;");
                sb.WriteLine($"OnPropertyChanged(val, \"{propertyName}\");");
            }

            sb.WriteLine($"private void TryInit{propertyName}()");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine($"if ({fieldName}Ob != null)");
                sb.WriteLine("    return;");
                sb.WriteLine($"{fieldName}Ob = new {concreteTypeString}(\"{propertyName}\",{fieldName}, {(saveSeparately ? "true" : "false")});");
                sb.WriteLine($"WatchCollection<{collectionTypeString}, {elemTypeString}>({fieldName}Ob);");
            }

            sb.WriteLine();
        }

        protected string GetCollectionTypeString(CollectionType colType, ImmutableArray<ITypeSymbol> typeSymbols)
        {
            var format = SymbolDisplayFormat.FullyQualifiedFormat;
            var typeIndex = colType switch
            {
                CollectionType.Array or CollectionType.List => 0,
                CollectionType.Dictionary => 1,
                _ => throw new NotSupportedException(),
            };
            var isSavable = IsTypeISavable(typeSymbols[typeIndex]);

            return colType switch
            {
                CollectionType.Array => isSavable
                    ? $"ObservableArraySavableBase<{typeSymbols[0].ToDisplayString(format)}>"
                    : $"ObservableArray<{typeSymbols[0].ToDisplayString(format)}>",
                CollectionType.List => isSavable
                    ? $"ObservableListSavableBase<{typeSymbols[0].ToDisplayString(format)}>"
                    : $"ObservableList<{typeSymbols[0].ToDisplayString(format)}>",
                CollectionType.Dictionary => $"ObservableDictionarySavable<{typeSymbols[0].ToDisplayString(format)}, {typeSymbols[1].ToDisplayString(format)}>",
                _ => throw new NotSupportedException()
            };
        }

        protected string GetCollectionConcreteTypeString(CollectionType colType, ImmutableArray<ITypeSymbol> typeSymbols)
        {
            var format = SymbolDisplayFormat.FullyQualifiedFormat;
            var typeIndex = colType switch
            {
                CollectionType.Array or CollectionType.List => 0,
                CollectionType.Dictionary => 1,
                _ => throw new NotSupportedException(),
            };
            var isSavable = IsTypeISavable(typeSymbols[typeIndex]);

            return colType switch
            {
                CollectionType.Array => isSavable
                    ? $"ObservableArraySavable<{typeSymbols[0].ToDisplayString(format)}>"
                    : $"ObservableArray<{typeSymbols[0].ToDisplayString(format)}>",
                CollectionType.List => isSavable
                    ? $"ObservableListSavable<{typeSymbols[0].ToDisplayString(format)}>"
                    : $"ObservableList<{typeSymbols[0].ToDisplayString(format)}>",
                CollectionType.Dictionary => $"ObservableDictionarySavable<{typeSymbols[0].ToDisplayString(format)}, {typeSymbols[1].ToDisplayString(format)}>",
                _ => throw new NotSupportedException()
            };
        }

        protected virtual void WriteImplementationsHead(ScriptBuilder sb, CodeGenerationContext ctx)
        {
            // ISerializeRoot Implementation
            if (_infoStore!.generateSerializeRootMode == 2)
            {
                sb.WriteLine("public Serializer? Serializer { get; private set; }");
                sb.WriteLine("public void SetSerializer(Serializer serializer) => Serializer = serializer;");
                sb.WriteLine();
            }
            // ISavable Implementation
            sb.WriteLine($"public event PropertyChangeEventHandler<{_infoStore!.className}> PropertyChanged;");
            sb.WriteLine();
            AddAttributePreventSerialize(sb, true);
            sb.WriteLine("public ISavable SvParent { get; private set; }");
            sb.WriteLine();
            AddAttributePreventSerialize(sb, false);
            sb.WriteLine("private string _svId;");
            sb.WriteLine("private bool _svIsDirty = true;");
            sb.WriteLine("private bool _svIsChildrenDirty = false;");
            sb.WriteLine();
            AddAttributePreventSerialize(sb, true);
            sb.WriteLine("public bool IsSelfDirty => _svIsDirty;");
            sb.WriteLine("public bool IsDirty => _svIsDirty || _svIsChildrenDirty;");
            AddAttributePreventSerialize(sb, true);
            sb.WriteLine("public string SvId");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("get => _svId;");
                sb.WriteLine("set");
                using (sb.CurlyBracketsScope())
                {
                    sb.WriteLine("OnSvIdChanging(ref value);");
                    sb.WriteLine("if (!EqualityComparer<string>.Default.Equals(_svId, value))");
                    using (sb.CurlyBracketsScope())
                    {
                        sb.WriteLine("var oldId = _svId;");
                        sb.WriteLine("_svId = value;");
                        sb.WriteLine("OnSvIdChanged();");
                        sb.WriteLine("OnPropertyChanged(value, \"SvId\");");
                    }
                }
            }
            sb.WriteLine();

            sb.WriteLine("partial void OnSvIdChanging(ref string svid);");
            sb.WriteLine("partial void OnSvIdChanged();");
            sb.WriteLine();
        }

        protected virtual void WriteImplementationsFoot(ScriptBuilder sb, CodeGenerationContext ctx)
        {
            sb.WriteLine("void ISavable.SetParent(ISavable parent)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("if (Equals(SvParent, parent)) return;");
                sb.WriteLine("SvParent = parent;");
                sb.WriteLine("(this as ISavable).SetDirty(true, true);");
            }

            sb.WriteLine();

            sb.WriteLine("void ISavable.SetDirty(bool dirty, bool recursively)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("_svIsDirty = dirty;");
                if (_infoStore!.savableMembers.Count > 0)
                {
                    sb.WriteLine("if (recursively)");
                    using (sb.CurlyBracketsScope())
                    {
                        sb.WriteLine("_svIsChildrenDirty = dirty;");
                        foreach (var prop in _infoStore!.savableMembers)
                        {
                            var fieldName = GetOriginName(prop);
                            if (_infoStore.separatedCollections.Contains(prop) || _infoStore.nonSeparatedCollections.Contains(prop))
                                fieldName += "Ob";
                            sb.WriteLine($"({fieldName} as ISavable)?.SetDirty(dirty, true);");
                        }
                    }

                }
            }

            sb.WriteLine();

            sb.WriteLine("private void OnPropertyChanged<T>(T value, string propName)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("_svIsDirty = true;");
                sb.WriteLine("PropertyChanged?.Invoke(this, propName);");
            }

            sb.WriteLine();

            sb.WriteLine("private void OnChildChanged<T>(T value, string propName)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("if (value is not ISavable sv || string.IsNullOrEmpty(sv.SvId))");
                sb.WriteLine("    return;");
                sb.WriteLine("var childName = sv.SvId;");
                var localSavables = _infoStore!.savableMembers.Except(_infoStore.separatedProperties).Except(_infoStore.separatedCollections).ToArray();
                if (localSavables.Length > 0)
                {
                    sb.WriteLine("switch(childName)");
                    using (sb.CurlyBracketsScope())
                    {
                        foreach (var propName in localSavables)
                        {
                            sb.WriteLine($"case \"{propName}\":");
                        }
                        using (sb.CurlyBracketsScope())
                        {
                            sb.WriteLine("_svIsDirty = true;");
                            sb.WriteLine("break;");
                        }
                        sb.WriteLine("default:");
                        using (sb.CurlyBracketsScope())
                        {
                            sb.WriteLine("_svIsChildrenDirty = true;");
                            sb.WriteLine("break;");
                        }
                    }
                }
                sb.WriteLine("PropertyChanged?.Invoke(this, childName);");
            }

            sb.WriteLine();

            sb.WriteLine("private void WatchChild<T>(T target, string propertyName)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("if (target is not ISavable<T> sv)");
                sb.WriteLine("    return;");
                sb.WriteLine("sv.SvId = propertyName;");
                sb.WriteLine("this.SetChild(sv);");
                sb.WriteLine("sv.PropertyChanged += OnChildChanged;");
            }

            sb.WriteLine();

            sb.WriteLine("private void UnwatchChild<T>(T target)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("if (target is not ISavable<T> sv)");
                sb.WriteLine("    return;");
                sb.WriteLine("sv.SetParent(null);");
                sb.WriteLine("sv.PropertyChanged -= OnChildChanged;");
            }

            sb.WriteLine();

            sb.WriteLine("private void OnChildDeserialized<T>(T target, string propertyName)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("if (target is not ISavable<T> sv)");
                sb.WriteLine("    return;");
                sb.WriteLine("sv.SvId = propertyName;");
                sb.WriteLine("this.ChildDeserialized(sv);");
                sb.WriteLine("sv.PropertyChanged += OnChildChanged;");
            }


            sb.WriteLine("private void OnCollectionDeserialized<TCol, TElem>(ObservableCollection<TCol, TElem> target)");
            sb.WriteLine("    where TCol : ObservableCollection<TCol, TElem>");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("this.ChildDeserialized(target);");
                sb.WriteLine("target.PropertyChanged += OnChildChanged;");
                sb.WriteLine("target.CollectionChanged += OnCollectionChanged;");
            }

            sb.WriteLine();

            sb.WriteLine("private void WatchCollection<TCol, TElem>(TCol target) where TCol: ObservableCollection<TCol, TElem>");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("if (target == null) return;");
                sb.WriteLine("target.PropertyChanged += OnChildChanged;");
                sb.WriteLine("target.CollectionChanged += OnCollectionChanged;");
            }

            sb.WriteLine();

            sb.WriteLine("private void UnwatchCollection<TCol, TElem>(TCol target) where TCol: ObservableCollection<TCol, TElem>");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("if (target == null) return;");
                sb.WriteLine("target.PropertyChanged -= OnChildChanged;");
                sb.WriteLine("target.CollectionChanged -= OnCollectionChanged;");
            }

            sb.WriteLine();

            sb.WriteLine("private void OnCollectionChanged<TCol, TElem>(CollectionChangeInfo<TCol, TElem> evt)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("if (evt.SourceCollection is not ISavable sv)");
                sb.WriteLine("    return;");
                sb.WriteLine("_svIsChildrenDirty = true;");
                sb.WriteLine("PropertyChanged?.Invoke(this, sv.SvId);");
            }

            sb.WriteLine();

            sb.WriteLine("public void Serialize(Serializer serializer, SerializeContext ctx)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("var isSelfDirty = IsSelfDirty;");
                sb.WriteLine("if (isSelfDirty)");
                using (sb.CurlyBracketsScope())
                {
                    sb.WriteLine("OnBeforeSerialize(serializer, ctx);");
                    sb.WriteLine("serializer.SaveNoPushPath(this, ctx);");
                }

                foreach (var prop in _infoStore!.separatedProperties)
                {
                    var fieldName = GetOriginName(prop);
                    sb.WriteLine($"{fieldName}?.TrySerialize(serializer, ctx);");
                }

                foreach (var name in _infoStore!.separatedCollections)
                {
                    var fieldName = GetOriginName(name);
                    sb.WriteLine($"{fieldName}Ob?.TrySerialize(serializer, ctx);");
                }

                sb.WriteLine("if (isSelfDirty) OnAfterSerialize(serializer, ctx);");
            }

            sb.WriteLine("partial void OnBeforeSerialize(Serializer serializer, SerializeContext ctx);");
            sb.WriteLine();

            sb.WriteLine("partial void OnAfterSerialize(Serializer serializer, SerializeContext ctx);");
            sb.WriteLine();

            sb.WriteLine("void ISavable.AfterDeserialize(Serializer serializer, SerializeContext ctx)");
            using (sb.CurlyBracketsScope())
            {
                var localSavables = _infoStore!.savableMembers.Except(_infoStore.separatedProperties).Except(_infoStore.separatedCollections).ToArray();
                foreach (var prop in localSavables)
                {
                    var fieldName = GetOriginName(prop);
                    sb.WriteLine($"OnChildDeserialized({fieldName}, \"{prop}\");");
                }

                foreach (var prop in _infoStore!.separatedProperties)
                {
                    var fieldName = GetOriginName(prop);
                    sb.WriteLine($"{fieldName} = serializer.Read<{_infoStore!.propTypeMappings[fieldName].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(ctx, \"{prop}\", PathBuilder.Type.Property);");
                    sb.WriteLine($"OnChildDeserialized({fieldName}, \"{prop}\");");
                }

                WriteLoadCollections(sb, _infoStore!.separatedCollections, true);
                WriteLoadCollections(sb, _infoStore!.nonSeparatedCollections, false);

                sb.WriteLine("OnAfterDeserialize(serializer, ctx);");
            }

            sb.WriteLine("partial void OnAfterDeserialize(Serializer serializer, SerializeContext ctx);");
            sb.WriteLine();
        }

        private void WriteLoadCollections(ScriptBuilder sb, HashSet<string> collections, bool isSeparated)
        {
            foreach (var name in collections)
            {
                var fieldName = GetOriginName(name);
                var (collectionType, typeParameters) = _infoStore!.collectionParameterMappings[fieldName];
                var typeIndex = collectionType switch
                {
                    CollectionType.Array or CollectionType.List => 0,
                    CollectionType.Dictionary => 1,
                    _ => throw new NotSupportedException("CollectionType: " + collectionType.ToString()),
                };
                var isSavable = IsTypeISavable(typeParameters[typeIndex]);
                var savableStr = isSavable ? "Savable" : "";
                var typeParametersStr = string.Join(", ", typeParameters.Select(symbol => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
                sb.WriteLine($"{fieldName}Ob = serializer.LoadCollection{savableStr}(ctx, \"{name}\", {(isSeparated ? "true" : "false")}, ref {fieldName});");
                sb.WriteLine($"OnCollectionDeserialized({fieldName}Ob);");
            }
        }

        protected virtual void AddAttributePreventSerialize(ScriptBuilder sb, bool isOnProperty)
        {
        }

        private string GetOriginName(string generatedName)
        {
            foreach (var kvp in _infoStore!.nameMappings)
            {
                if (kvp.Value == generatedName)
                    return kvp.Key;
            }

            throw new ArgumentException(generatedName);
        }
    }
}