using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace Salvavida.Generator
{
    public class BasicCodeGenerator : ICodeGenerator
    {
        internal readonly string[] AlternateNameTemplates = new[] { "Sv{0}", "{0}Ob" };
        protected CodeGenInfoStore? _infoStore;

        public virtual bool CanGenerate(CodeGenerationContext ctx) => true;

        public string Generate(CodeGenerationContext ctx)
        {
            _infoStore = new CodeGenInfoStore();
            var alreadySR = CodeGenHelper.GetIsAlreadySavableRoot(ctx.TypeSymbol);
            if (!alreadySR && CodeGenHelper.GetIsSavableRoot(ctx.TypeSymbol, true))
            {
                if (CodeGenHelper.GetHasBaseClasse(ctx.TypeSymbol))
                    _infoStore.generateSerializeRootMode++;
                _infoStore.generateSerializeRootMode++;
            }
            try
            {
                var sb = new ScriptBuilder();
                sb.WriteLine("// <auto-generated/>");
                sb.WriteLine("// This code is Generated by Salvavida Library.");
                sb.WriteLine("#nullable disable");
                sb.WriteLine("#pragma warning disable");
                sb.WriteLine("using Salvavida;");
                sb.WriteLine("using System.Collections.Generic;");
                WriteUsings(sb, ctx);
                sb.WriteLine();
                BeforeWriteNamespace(sb, ctx);
                WriteNamespace(sb, ctx, out var nsIndent);
                BeforeWriteClass(sb, ctx);
                WriteClass(sb, ctx);
                WriteClassBody(sb, ctx);
                sb.EndCurlyBrackets();
                if (nsIndent) sb.EndCurlyBrackets();
                return sb.ToString();
            }
            finally
            {
                _infoStore = null;
            }
        }

        private void WriteNamespace(ScriptBuilder sb, CodeGenerationContext ctx, out bool hasCurlyBrackets)
        {
            hasCurlyBrackets = false;
            var ns = ctx.TypeSymbol.ContainingNamespace;
            if (ns == null || ns.IsGlobalNamespace)
                return;

            if (ctx.LanguageVersion >= LanguageVersion.CSharp10)
            {
                sb.WriteLine($"namespace {ns.ToDisplayString()};");
                sb.WriteLine();
            }
            else
            {
                sb.WriteLine($"namespace {ns.ToDisplayString()}");
                sb.BeginCurlyBrackets(true);
                hasCurlyBrackets = true;
            }
        }

        private void WriteClass(ScriptBuilder sb, CodeGenerationContext ctx)
        {
            var className = ctx.TypeSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            _infoStore!.className = className;

            sb.Write($"sealed partial class {className} : ");
            if (_infoStore!.generateSerializeRootMode > 0)
            {
                if (_infoStore!.generateSerializeRootMode == 1)
                    sb.Write("Salvavida.DefaultImpl.SerializeRoot, ", true);
                else
                {
                    sb.Write(CodeGenHelper.INTERFACE_NAME_ISERIALIZEROOT, true);
                    sb.Write(", ", true);
                }
            }
            sb.Write($"ISavable<{className}>", true);
            sb.WriteLine();
            sb.BeginCurlyBrackets();
        }

        protected virtual void WriteUsings(ScriptBuilder sb, CodeGenerationContext ctx)
        {
        }

        protected virtual void BeforeWriteNamespace(ScriptBuilder sb, CodeGenerationContext ctx)
        {
        }

        protected virtual void BeforeWriteClass(ScriptBuilder sb, CodeGenerationContext ctx)
        {
        }

        protected virtual void WriteClassBody(ScriptBuilder sb, CodeGenerationContext ctx)
        {
            WriteImplementationsHead(sb, ctx);
            var typeSymbol = ctx.TypeSymbol;
            var membersList = new List<ISymbol>();
            ITypeSymbol? parentType = typeSymbol;
            var i = 0;
            while (parentType != null)
            {
                IEnumerable<ISymbol> mems = parentType.GetMembers();
                if (i++ > 0)
                    mems = mems.Where(x => x.DeclaredAccessibility != Accessibility.Private);
                foreach (var mem in mems)
                {
                    membersList.Add(mem);
                    _infoStore!.existingPropertyNames.Add(mem.Name);
                }
                parentType = parentType.BaseType;
            }

            var allMembers = membersList.ToImmutableArray();

            foreach (var member in allMembers)
            {
                if (member is not IFieldSymbol fieldSymbol)
                    continue;
                HandleField(sb, fieldSymbol, ctx);
            }

            foreach (var member in allMembers)
            {
                if (member is not IPropertySymbol propSymbol)
                    continue;
                HandleProperty(sb, propSymbol, ctx);
            }

            foreach (var member in allMembers)
            {
                if (member is not IMethodSymbol methodSymbol)
                    continue;
                HandleMethod(sb, methodSymbol, ctx);
            }

            WriteImplementationsFoot(sb, ctx);
        }

        protected virtual void HandleField(ScriptBuilder sb, IFieldSymbol field, CodeGenerationContext ctx)
        {
            if (field.IsReadOnly || field.IsAbstract || field.IsConst || field.IsStatic)
                return;
            HandleFieldOrProp(sb, field, ctx);
        }

        protected virtual void HandleProperty(ScriptBuilder sb, IPropertySymbol prop, CodeGenerationContext ctx)
        {
            if (prop.IsReadOnly || prop.IsIndexer || prop.IsWriteOnly || prop.IsAbstract || prop.IsStatic)
                return;
            HandleFieldOrProp(sb, prop, ctx);
        }

        protected void HandleFieldOrProp(ScriptBuilder sb, ISymbol symbol, CodeGenerationContext ctx)
        {
            AttributeData? propNameAttr = null;
            AttributeData? ignoreAttr = null;
            AttributeData? saveSeparatelyAttr = null;

            var attrs = symbol.GetAttributes();

            foreach (var attrData in attrs)
            {
                var attrSymbol = attrData.AttributeClass!;
                var attrName = attrSymbol.ToDisplayString();
                if (attrName == CodeGenHelper.PROPERTY_NAME_ATTRIBUTE_NAME)
                    propNameAttr = attrData;
                else if (attrName == CodeGenHelper.IGNORE_ATTRIBUTE_NAME)
                    ignoreAttr = attrData;
                else if (attrName == CodeGenHelper.SAVE_SEPARATELY_ATTRIBUTE_NAME)
                    saveSeparatelyAttr = attrData;
            }

            if (ignoreAttr != null)
                return;

            string? attrPropName = null;
            if (propNameAttr != null)
            {
                var nameArg = propNameAttr.ConstructorArguments[0];
                attrPropName = nameArg.Value as string;
            }

            var fieldName = symbol.Name;
            if (string.IsNullOrEmpty(fieldName))
                return;
            string propertyName;
            if (string.IsNullOrEmpty(attrPropName))
            {
                var tempName = CodeGenHelper.GetPropertyName(fieldName.AsSpan());
                if (string.IsNullOrEmpty(tempName))
                {
                    ctx.SourceProductionContext.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.InvalidMemberName,
                        propNameAttr!.ApplicationSyntaxReference?.GetSyntax().GetLocation(), fieldName));
                    return;
                }
                else
                    propertyName = tempName!;
            }
            else
            {
                propertyName = attrPropName!;
            }

            var templateIndex = 0;
            while (_infoStore!.existingPropertyNames.Contains(propertyName))
            {
                if (templateIndex >= AlternateNameTemplates.Length)
                {
                    ctx.SourceProductionContext.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.AllCandidateNamesAreUnavailable,
                        symbol.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax().GetLocation(), fieldName));
                    return;
                }

                propertyName = string.Format(AlternateNameTemplates[templateIndex++], propertyName);
            }

            _infoStore!.existingPropertyNames.Add(propertyName);

            var typeSymbol = symbol switch
            {
                IFieldSymbol fs => fs.Type,
                IPropertySymbol ps => ps.Type,
                _ => throw new NotSupportedException(symbol.GetType().Name)
            };

            var collectionType = CodeGenHelper.GetCollectionType(ctx, typeSymbol, out var elemTypeSymbols);
            var saveSeparately = saveSeparatelyAttr != null;
            _infoStore!.nameMappings[fieldName] = propertyName;
            if (collectionType == CollectionType.None)
            {
                _infoStore.propTypeMappings[fieldName] = typeSymbol;
                if (saveSeparately)
                {
                    _infoStore!.separatedProperties.Add(propertyName);
                    _infoStore!.internalSeparatedMembers.Add(fieldName);
                }

                WriteProperty(sb, ctx, propertyName, fieldName, typeSymbol, saveSeparately);
            }
            else
            {
                _infoStore!.collectionParameterMappings[fieldName] = (collectionType, elemTypeSymbols);
                if (saveSeparately)
                {
                    //var savableElement = CodeGenHelper.TryGetAttribute(ctx, , SalvavidaGenerator.SALVAVIDA_ATTRIBUTE)
                    // TODO: to check if elemTypeSymbols.Last() implemented ISavable or not
                    _infoStore!.separatedCollections.Add(propertyName, false);
                    _infoStore!.internalSeparatedMembers.Add(fieldName);
                }

                var collectionTypeString = GetCollectionTypeString(collectionType, elemTypeSymbols);
                WriteCollectionProperty(sb, ctx, propertyName, fieldName,
                    typeSymbol, collectionTypeString, saveSeparately);
            }
        }

        protected virtual void HandleMethod(ScriptBuilder sb, IMethodSymbol method, CodeGenerationContext ctx)
        {
        }

        protected bool IsTypeISavable(ITypeSymbol typeSymbol)
        {
            if (!_infoStore!.savableTypes.TryGetValue(typeSymbol, out var result))
            {
                result = CodeGenHelper.GetIsSavable(typeSymbol);
                _infoStore!.savableTypes[typeSymbol] = result;
            }

            return result;
        }

        protected virtual void WriteProperty(ScriptBuilder sb, CodeGenerationContext ctx, string propertyName, string fieldName, ITypeSymbol typeSymbol, bool saveSeparately)
        {
            var typeFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            AddAttributePreventSerialize(sb, false);
            sb.WriteLine($"public {typeFullName} {propertyName}");
            var savabeType = IsTypeISavable(typeSymbol);
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("get");
                using (sb.CurlyBracketsScope())
                {
                    if (savabeType)
                    {
                        sb.WriteLine($"if ({fieldName} is ISavable sv && sv.SvParent == null)");
                        sb.WriteLine($"    WatchChild({fieldName}, \"{propertyName}\");");
                    }

                    sb.WriteLine($"return {fieldName};");
                }

                sb.WriteLine("set");
                using (sb.CurlyBracketsScope())
                {
                    sb.WriteLine($"if (!EqualityComparer<{typeFullName}>.Default.Equals({fieldName}, value))");
                    using (sb.CurlyBracketsScope())
                    {
                        if (savabeType)
                            sb.WriteLine($"UnwatchChild({fieldName});");
                        sb.WriteLine($"{fieldName} = value;");
                        if (savabeType)
                            sb.WriteLine($"WatchChild(value, \"{propertyName}\");");
                        sb.WriteLine($"OnPropertyChanged(value, \"{propertyName}\");");
                    }
                }
            }

            sb.WriteLine();
        }

        protected virtual void WriteCollectionProperty(ScriptBuilder sb, CodeGenerationContext ctx, string propertyName, string fieldName,
            ITypeSymbol typeSymbol, string collectionTypeString, bool saveSeparately)
        {
            AddAttributePreventSerialize(sb, false);
            sb.WriteLine($"private {collectionTypeString} {fieldName}Ob;");
            AddAttributePreventSerialize(sb, false);
            sb.WriteLine($"public {collectionTypeString} {propertyName}");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine($"get");
                using (sb.CurlyBracketsScope())
                {
                    sb.WriteLine($"if ({fieldName} == null) return null;");
                    sb.WriteLine($"TryInit{propertyName}();");
                    sb.WriteLine($"return {fieldName}Ob;");
                }
            }

            sb.WriteLine();
            sb.WriteLine($"public void Set{propertyName}({typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} val)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine($"TryInit{propertyName}();");
                sb.WriteLine($"{fieldName}Ob.SwapSource(val);");
                sb.WriteLine($"{fieldName} = val;");
                sb.WriteLine($"OnPropertyChanged(val, \"{propertyName}\");");
            }

            sb.WriteLine($"private void TryInit{propertyName}()");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine($"if ({fieldName}Ob != null)");
                sb.WriteLine("    return;");
                sb.WriteLine($"{fieldName}Ob = new {collectionTypeString}(\"{propertyName}\",{fieldName}, {(saveSeparately ? "true" : "false")});");
                sb.WriteLine($"WatchChild({fieldName}Ob, \"{propertyName}\");");
                sb.WriteLine($"this.SetChild({fieldName}Ob);");
            }

            sb.WriteLine();
        }

        protected string GetCollectionTypeString(CollectionType colType, ImmutableArray<ITypeSymbol> typeSymbols)
        {
            var format = SymbolDisplayFormat.FullyQualifiedFormat;
            var typeIndex = colType switch
            {
                CollectionType.Array or CollectionType.List => 0,
                CollectionType.Dictionary => 1,
                _ => throw new NotSupportedException(),
            };
            var isSavable = CodeGenHelper.GetIsSavable(typeSymbols[typeIndex]);
            var savableStr = isSavable ? "Savable" : "";

            return colType switch
            {
                CollectionType.Array => $"ObservableArray{savableStr}<{typeSymbols[0].ToDisplayString(format)}>",
                CollectionType.List => $"ObservableList{savableStr}<{typeSymbols[0].ToDisplayString(format)}>",
                CollectionType.Dictionary => $"ObservableDictionary{savableStr}<{typeSymbols[0].ToDisplayString(format)}, {typeSymbols[1].ToDisplayString(format)}>",
                _ => throw new NotSupportedException()
            };
        }

        protected virtual void WriteImplementationsHead(ScriptBuilder sb, CodeGenerationContext ctx)
        {
            // ISerializeRoot Implementation
            if (_infoStore!.generateSerializeRootMode == 2)
            {
                sb.WriteLine("public Serializer? Serializer { get; private set; }");
                sb.WriteLine("public void SetSerializer(Serializer serializer) => Serializer = serializer;");
                sb.WriteLine();
            }
            // ISavable Implementation
            sb.WriteLine($"public event PropertyChangeEventHandler<{_infoStore!.className}> PropertyChanged;");
            sb.WriteLine();
            AddAttributePreventSerialize(sb, true);
            sb.WriteLine("public ISavable SvParent { get; private set; }");
            sb.WriteLine();
            AddAttributePreventSerialize(sb, false);
            sb.WriteLine("private string _svId;");
            sb.WriteLine("private bool _svIsDirty = true;");
            sb.WriteLine();
            AddAttributePreventSerialize(sb, true);
            sb.WriteLine("public bool IsDirty => _svIsDirty;");
            AddAttributePreventSerialize(sb, true);
            sb.WriteLine("public string SvId");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("get => _svId;");
                sb.WriteLine("set");
                using (sb.CurlyBracketsScope())
                {
                    sb.WriteLine("OnSvIdChanging(ref value);");
                    sb.WriteLine("if (!EqualityComparer<string>.Default.Equals(_svId, value))");
                    using (sb.CurlyBracketsScope())
                    {
                        sb.WriteLine("var oldId = _svId;");
                        sb.WriteLine("_svId = value;");
                        sb.WriteLine("OnSvIdChanged();");
                        //sb.WriteLine("this.TryUpdateId(oldId);");
                        sb.WriteLine("OnPropertyChanged(value, \"SvId\");");
                    }
                }
            }
            sb.WriteLine("public string SvIdDeserialized { get; private set; }");
            sb.WriteLine();

            sb.WriteLine("partial void OnSvIdChanging(ref string svid);");
            sb.WriteLine("partial void OnSvIdChanged();");
            sb.WriteLine();
        }

        protected virtual void WriteImplementationsFoot(ScriptBuilder sb, CodeGenerationContext ctx)
        {
            sb.WriteLine("void ISavable.SetParent(ISavable parent)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("if (Equals(SvParent, parent)) return;");
                sb.WriteLine("SvParent = parent;");
                sb.WriteLine("(this as ISavable).SetDirty(true, true);");
            }

            sb.WriteLine();

            sb.WriteLine("void ISavable.SetDirty(bool dirty, bool recursively)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("_svIsDirty = dirty;");
                if (_infoStore!.separatedProperties.Count > 0 || _infoStore!.separatedCollections.Count > 0)
                {
                    sb.WriteLine("if (recursively)");
                    {
                        using (sb.CurlyBracketsScope())
                        {
                            foreach (var prop in _infoStore!.separatedProperties)
                            {
                                var fieldName = GetOriginName(prop);
                                sb.WriteLine($"({fieldName} as ISavable)?.SetDirty(dirty, true);");
                            }

                            foreach (var kvp in _infoStore!.separatedCollections)
                            {
                                sb.WriteLine($"({kvp.Key} as ISavable)?.SetDirty(dirty, true);");
                            }
                        }
                    }
                }
            }

            sb.WriteLine();

            sb.Write("private static readonly string[] _separatedProperties = ");
            if (_infoStore!.separatedProperties.Count > 0)
            {
                sb.Write("new[] { ", true);
                foreach (var propName in _infoStore.separatedProperties)
                {
                    sb.Write("\"", true);
                    sb.Write(propName, true);
                    sb.Write("\", ", true);
                }

                sb.WriteLine("};", true);
            }
            else
                sb.WriteLine("null;", true);

            sb.Write("private static readonly string[] _separatedCollections = ");
            if (_infoStore!.separatedCollections.Count > 0)
            {
                sb.Write("new[] { ", true);
                foreach (var kvp in _infoStore.separatedCollections)
                {
                    sb.Write("\"", true);
                    sb.Write(kvp.Key, true);
                    sb.Write("\", ", true);
                }

                sb.WriteLine("};", true);
            }
            else
                sb.WriteLine("null;", true);

            sb.WriteLine("private void OnPropertyChanged<T>(T value, string propName)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("_svIsDirty = true;");
                //sb.WriteLine("this.TrySave(propName, value, typeof(T), _separatedProperties, _separatedCollections);");
                sb.WriteLine("PropertyChanged?.Invoke(this, propName);");
            }

            sb.WriteLine();

            sb.WriteLine("private void OnChildChanged<T>(T value, string propName)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("if (value is not ISavable sv || string.IsNullOrEmpty(sv.SvId))");
                sb.WriteLine("    return;");
                sb.WriteLine("_svIsDirty = true;");
                //sb.WriteLine("this.TrySave(sv.SvId, sv, typeof(T), _separatedProperties, _separatedCollections);");
                sb.WriteLine("PropertyChanged?.Invoke(this, sv.SvId);");
            }

            sb.WriteLine();

            sb.WriteLine("private void WatchChild<T>(T target, string propertyName)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("if (target is not ISavable<T> sv)");
                sb.WriteLine("    return;");
                sb.WriteLine("sv.SvId = propertyName;");
                sb.WriteLine("this.SetChild(sv);");
                sb.WriteLine("sv.PropertyChanged += OnChildChanged;");
            }

            sb.WriteLine();

            sb.WriteLine("private void UnwatchChild<T>(T target)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("if (target is not ISavable<T> sv)");
                sb.WriteLine("    return;");
                sb.WriteLine("sv.SetParent(null);");
                sb.WriteLine("sv.PropertyChanged -= OnChildChanged;");
            }

            sb.WriteLine();

            //sb.WriteLine("public void Invalidate(bool recursively)");
            //using (sb.CurlyBracketsScope())
            //{
            //    sb.WriteLine("(this as ISavable).SetDirty(true, recursively);");
            //    sb.WriteLine("var serializer = this.GetSerializer();");
            //    sb.WriteLine("if (serializer == null || string.IsNullOrEmpty(SvId))");
            //    sb.WriteLine("    return;");
            //    if (CodeGenHelper.GetIsSavableRoot(ctx.TypeSymbol, false))
            //        sb.WriteLine("serializer.FreshSave(this);");
            //    else
            //        sb.WriteLine("PropertyChanged?.Invoke(this, SvId);");
            //}

            sb.WriteLine("void ISavable.BeforeSerialize(Serializer serializer, SerializeContext ctx)");
            using (sb.CurlyBracketsScope())
            {
                sb.WriteLine("OnBeforeSerialize(serializer, ctx);");
            }

            sb.WriteLine("partial void OnBeforeSerialize(Serializer serializer, SerializeContext ctx);");
            sb.WriteLine();

            sb.WriteLine("void ISavable.AfterSerialize(Serializer serializer, SerializeContext ctx)");
            using (sb.CurlyBracketsScope())
            {
                if (_infoStore!.separatedProperties.Count > 0 || _infoStore!.separatedCollections.Count > 0)
                {
                    foreach (var prop in _infoStore!.separatedProperties)
                    {
                        var fieldName = GetOriginName(prop);
                        var propType = _infoStore.propTypeMappings[fieldName];
                        //sb.WriteLine($"this.TrySaveSeparatedProperty(serializer, ctx, \"{prop}\", {fieldName}, typeof({propType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}));");
                    }

                    foreach (var kvp in _infoStore!.separatedCollections)
                    {
                        //sb.WriteLine($"{kvp.Key}?.TrySave(serializer, ctx);");
                    }
                }

                foreach (var kvp in _infoStore!.propTypeMappings)
                {
                    if (!_infoStore.savableTypes[kvp.Value] || _infoStore.internalSeparatedMembers.Contains(kvp.Key))
                        continue;
                    sb.WriteLine($"({kvp.Key} as ISavable).PropertyAfterSerialize(serializer, ctx,  \"{_infoStore!.nameMappings[kvp.Key]}\");");
                }

                sb.WriteLine("OnAfterSerialize(serializer, ctx);");
                sb.WriteLine("SvIdDeserialized = null;");
            }

            sb.WriteLine("partial void OnAfterSerialize(Serializer serializer, SerializeContext ctx);");
            sb.WriteLine();

            sb.WriteLine("void ISavable.AfterDeserialize(Serializer serializer, SerializeContext ctx)");
            using (sb.CurlyBracketsScope())
            {
                if (_infoStore!.separatedProperties.Count > 0 || _infoStore!.separatedCollections.Count > 0)
                {
                    foreach (var prop in _infoStore!.separatedProperties)
                    {
                        var fieldName = GetOriginName(prop);
                        sb.WriteLine($"{fieldName} = serializer.ReadObject<{_infoStore!.propTypeMappings[fieldName].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(ctx, \"{prop}\", PathBuilder.Type.Property);");
                    }

                    foreach (var kvp in _infoStore!.separatedCollections)
                    {
                        var fieldName = GetOriginName(kvp.Key);
                        var (collectionType, typeParameters) = _infoStore!.collectionParameterMappings[fieldName];
                        var typeParametersStr = string.Join(", ", typeParameters.Select(symbol => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
                        sb.Write(fieldName);
                        sb.Write(" = serializer.", true);
                        sb.Write(collectionType switch
                        {
                            CollectionType.Array => $"ReadArray",
                            CollectionType.List => $"ReadList",
                            CollectionType.Dictionary => $"ReadDict",
                            _ => throw new NotSupportedException("CollectionType: " + collectionType.ToString()),
                        }, true);

                        var checkIsSavableSyntax = $"SvHelper.CheckIsSavable<{typeParameters.Last().ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>()";

                        sb.WriteLine($"<{typeParametersStr}>(ctx, \"{kvp.Key}\", {checkIsSavableSyntax});", true);
                        sb.WriteLine($"({kvp.Key} as ISavable).SetDirty(false, false);");
                    }
                }

                foreach (var kvp in _infoStore!.propTypeMappings)
                {
                    if (!_infoStore.savableTypes[kvp.Value] || _infoStore.internalSeparatedMembers.Contains(kvp.Key))
                        continue;
                    sb.WriteLine($"({kvp.Key} as ISavable).PropertyAfterDeserialize(serializer, ctx, \"{_infoStore!.nameMappings[kvp.Key]}\");");
                }

                sb.WriteLine("OnAfterDeserialize(serializer, ctx);");
                sb.WriteLine("SvIdDeserialized = SvId;");
            }

            sb.WriteLine("partial void OnAfterDeserialize(Serializer serializer, SerializeContext ctx);");
            sb.WriteLine();
        }

        protected virtual void AddAttributePreventSerialize(ScriptBuilder sb, bool isOnProperty)
        {
        }

        private string GetOriginName(string generatedName)
        {
            foreach (var kvp in _infoStore!.nameMappings)
            {
                if (kvp.Value == generatedName)
                    return kvp.Key;
            }

            throw new ArgumentException(generatedName);
        }
    }
}